version: '3.1'
services:

  cocophpapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: ywemay/coco-containers-phpapi
    container_name: coco-containers-phpapi
    ports:
      - 8086:80
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
    links:
      - cocomysql
    environment:
      DB_LINK: 'mysql://cococtnr:cocopass@cocomysql:3306/coco'
      JWT_KEY: "anJWTTokenSoThatCanEncrypt"

  cocomysql:
    image: mysql:5.7
    restart: always
    container_name: coco-containers-mysql
    environment:
      MYSQL_DATABASE: 'coco'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'cococtnr'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'cocopass'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'superpass'
    volumes:
      - ./my-db:/var/lib/mysql
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 23306:3306
    expose:
      # Opens port 3306 on the container
      - '3306'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
